// marketdata_v2.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: market.proto

package market

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ---- Enums ----
type Venue int32

const (
	Venue_VENUE_UNSPECIFIED Venue = 0
	Venue_VENUE_CEX         Venue = 1
	Venue_VENUE_DEX         Venue = 2
)

// Enum value maps for Venue.
var (
	Venue_name = map[int32]string{
		0: "VENUE_UNSPECIFIED",
		1: "VENUE_CEX",
		2: "VENUE_DEX",
	}
	Venue_value = map[string]int32{
		"VENUE_UNSPECIFIED": 0,
		"VENUE_CEX":         1,
		"VENUE_DEX":         2,
	}
)

func (x Venue) Enum() *Venue {
	p := new(Venue)
	*p = x
	return p
}

func (x Venue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Venue) Descriptor() protoreflect.EnumDescriptor {
	return file_market_proto_enumTypes[0].Descriptor()
}

func (Venue) Type() protoreflect.EnumType {
	return &file_market_proto_enumTypes[0]
}

func (x Venue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Venue.Descriptor instead.
func (Venue) EnumDescriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{0}
}

type Instrument int32

const (
	Instrument_INSTRUMENT_UNSPECIFIED Instrument = 0
	Instrument_INSTRUMENT_SPOT        Instrument = 1
	Instrument_INSTRUMENT_PERPETUAL   Instrument = 2
	Instrument_INSTRUMENT_SWAP        Instrument = 3
	Instrument_INSTRUMENT_OPTION      Instrument = 4 // reserved for future use
)

// Enum value maps for Instrument.
var (
	Instrument_name = map[int32]string{
		0: "INSTRUMENT_UNSPECIFIED",
		1: "INSTRUMENT_SPOT",
		2: "INSTRUMENT_PERPETUAL",
		3: "INSTRUMENT_SWAP",
		4: "INSTRUMENT_OPTION",
	}
	Instrument_value = map[string]int32{
		"INSTRUMENT_UNSPECIFIED": 0,
		"INSTRUMENT_SPOT":        1,
		"INSTRUMENT_PERPETUAL":   2,
		"INSTRUMENT_SWAP":        3,
		"INSTRUMENT_OPTION":      4,
	}
)

func (x Instrument) Enum() *Instrument {
	p := new(Instrument)
	*p = x
	return p
}

func (x Instrument) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Instrument) Descriptor() protoreflect.EnumDescriptor {
	return file_market_proto_enumTypes[1].Descriptor()
}

func (Instrument) Type() protoreflect.EnumType {
	return &file_market_proto_enumTypes[1]
}

func (x Instrument) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Instrument.Descriptor instead.
func (Instrument) EnumDescriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{1}
}

type Aggressor int32

const (
	Aggressor_AGGR_UNKNOWN Aggressor = 0
	Aggressor_AGGR_BUY     Aggressor = 1
	Aggressor_AGGR_SELL    Aggressor = 2
)

// Enum value maps for Aggressor.
var (
	Aggressor_name = map[int32]string{
		0: "AGGR_UNKNOWN",
		1: "AGGR_BUY",
		2: "AGGR_SELL",
	}
	Aggressor_value = map[string]int32{
		"AGGR_UNKNOWN": 0,
		"AGGR_BUY":     1,
		"AGGR_SELL":    2,
	}
)

func (x Aggressor) Enum() *Aggressor {
	p := new(Aggressor)
	*p = x
	return p
}

func (x Aggressor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Aggressor) Descriptor() protoreflect.EnumDescriptor {
	return file_market_proto_enumTypes[2].Descriptor()
}

func (Aggressor) Type() protoreflect.EnumType {
	return &file_market_proto_enumTypes[2]
}

func (x Aggressor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Aggressor.Descriptor instead.
func (Aggressor) EnumDescriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{2}
}

// ---- Common header ----
type Header struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exchange identifier: e.g. "Binance", "PancakeSwapV3"
	Exchange string `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	// Unified symbol: e.g. "ETHUSDT", "BNB-USDT" (keep your house-style)
	Symbol     string     `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Venue      Venue      `protobuf:"varint,3,opt,name=venue,proto3,enum=md.Venue" json:"venue,omitempty"`
	Instrument Instrument `protobuf:"varint,4,opt,name=instrument,proto3,enum=md.Instrument" json:"instrument,omitempty"`
	// Monotonic-ish, event emission time in ns (UTC).
	TsNs int64 `protobuf:"varint,5,opt,name=ts_ns,json=tsNs,proto3" json:"ts_ns,omitempty"`
	// Schema version for the event family (bump when breaking).
	SchemaVersion uint32 `protobuf:"varint,6,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// Optional chain context for DEX (e.g., "BSC"), else empty.
	Chain string `protobuf:"bytes,7,opt,name=chain,proto3" json:"chain,omitempty"`
	// Optional: raw pool address for DEX tick source.
	PoolAddress   string `protobuf:"bytes,8,opt,name=pool_address,json=poolAddress,proto3" json:"pool_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *Header) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Header) GetVenue() Venue {
	if x != nil {
		return x.Venue
	}
	return Venue_VENUE_UNSPECIFIED
}

func (x *Header) GetInstrument() Instrument {
	if x != nil {
		return x.Instrument
	}
	return Instrument_INSTRUMENT_UNSPECIFIED
}

func (x *Header) GetTsNs() int64 {
	if x != nil {
		return x.TsNs
	}
	return 0
}

func (x *Header) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Header) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *Header) GetPoolAddress() string {
	if x != nil {
		return x.PoolAddress
	}
	return ""
}

// ---- Normalized events ----
type TickL1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Best bid/ask. If not available (DEX mark-only), set bid/ask = 0 and use mid.
	Bid float64 `protobuf:"fixed64,1,opt,name=bid,proto3" json:"bid,omitempty"`
	Ask float64 `protobuf:"fixed64,2,opt,name=ask,proto3" json:"ask,omitempty"`
	Mid float64 `protobuf:"fixed64,3,opt,name=mid,proto3" json:"mid,omitempty"`
	// Optional size at best.
	BidSize float64 `protobuf:"fixed64,4,opt,name=bid_size,json=bidSize,proto3" json:"bid_size,omitempty"`
	AskSize float64 `protobuf:"fixed64,5,opt,name=ask_size,json=askSize,proto3" json:"ask_size,omitempty"`
	// Optional auxiliary metrics.
	Twap          float64 `protobuf:"fixed64,10,opt,name=twap,proto3" json:"twap,omitempty"`           // DEX short-window twap if computed, else 0
	Liquidity     float64 `protobuf:"fixed64,11,opt,name=liquidity,proto3" json:"liquidity,omitempty"` // DEX liquidity approximation if available, else 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickL1) Reset() {
	*x = TickL1{}
	mi := &file_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickL1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickL1) ProtoMessage() {}

func (x *TickL1) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickL1.ProtoReflect.Descriptor instead.
func (*TickL1) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{1}
}

func (x *TickL1) GetBid() float64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *TickL1) GetAsk() float64 {
	if x != nil {
		return x.Ask
	}
	return 0
}

func (x *TickL1) GetMid() float64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *TickL1) GetBidSize() float64 {
	if x != nil {
		return x.BidSize
	}
	return 0
}

func (x *TickL1) GetAskSize() float64 {
	if x != nil {
		return x.AskSize
	}
	return 0
}

func (x *TickL1) GetTwap() float64 {
	if x != nil {
		return x.Twap
	}
	return 0
}

func (x *TickL1) GetLiquidity() float64 {
	if x != nil {
		return x.Liquidity
	}
	return 0
}

type Funding struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MarkPrice            float64                `protobuf:"fixed64,1,opt,name=mark_price,json=markPrice,proto3" json:"mark_price,omitempty"`
	IndexPrice           float64                `protobuf:"fixed64,2,opt,name=index_price,json=indexPrice,proto3" json:"index_price,omitempty"`
	EstimatedSettlePrice float64                `protobuf:"fixed64,3,opt,name=estimated_settle_price,json=estimatedSettlePrice,proto3" json:"estimated_settle_price,omitempty"`
	FundingRate          float64                `protobuf:"fixed64,4,opt,name=funding_rate,json=fundingRate,proto3" json:"funding_rate,omitempty"`              // per-period rate (e.g., 8h)
	NextFundingTime      int64                  `protobuf:"varint,5,opt,name=next_funding_time,json=nextFundingTime,proto3" json:"next_funding_time,omitempty"` // ms since epoch (exchange native)
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Funding) Reset() {
	*x = Funding{}
	mi := &file_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Funding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Funding) ProtoMessage() {}

func (x *Funding) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Funding.ProtoReflect.Descriptor instead.
func (*Funding) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{2}
}

func (x *Funding) GetMarkPrice() float64 {
	if x != nil {
		return x.MarkPrice
	}
	return 0
}

func (x *Funding) GetIndexPrice() float64 {
	if x != nil {
		return x.IndexPrice
	}
	return 0
}

func (x *Funding) GetEstimatedSettlePrice() float64 {
	if x != nil {
		return x.EstimatedSettlePrice
	}
	return 0
}

func (x *Funding) GetFundingRate() float64 {
	if x != nil {
		return x.FundingRate
	}
	return 0
}

func (x *Funding) GetNextFundingTime() int64 {
	if x != nil {
		return x.NextFundingTime
	}
	return 0
}

type Fee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MakerRate     float64                `protobuf:"fixed64,1,opt,name=maker_rate,json=makerRate,proto3" json:"maker_rate,omitempty"` // ratio (e.g., 0.001)
	TakerRate     float64                `protobuf:"fixed64,2,opt,name=taker_rate,json=takerRate,proto3" json:"taker_rate,omitempty"` // ratio
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fee) Reset() {
	*x = Fee{}
	mi := &file_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fee) ProtoMessage() {}

func (x *Fee) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fee.ProtoReflect.Descriptor instead.
func (*Fee) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{3}
}

func (x *Fee) GetMakerRate() float64 {
	if x != nil {
		return x.MakerRate
	}
	return 0
}

func (x *Fee) GetTakerRate() float64 {
	if x != nil {
		return x.TakerRate
	}
	return 0
}

type Trade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Size          float64                `protobuf:"fixed64,2,opt,name=size,proto3" json:"size,omitempty"`
	Aggressor     Aggressor              `protobuf:"varint,3,opt,name=aggressor,proto3,enum=md.Aggressor" json:"aggressor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_market_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{4}
}

func (x *Trade) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Trade) GetSize() float64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Trade) GetAggressor() Aggressor {
	if x != nil {
		return x.Aggressor
	}
	return Aggressor_AGGR_UNKNOWN
}

// ---- Envelope ----
type MarketData struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*MarketData_Tick
	//	*MarketData_Funding
	//	*MarketData_Fee
	//	*MarketData_Trade
	Data          isMarketData_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketData) Reset() {
	*x = MarketData{}
	mi := &file_market_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketData) ProtoMessage() {}

func (x *MarketData) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketData.ProtoReflect.Descriptor instead.
func (*MarketData) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{5}
}

func (x *MarketData) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *MarketData) GetData() isMarketData_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MarketData) GetTick() *TickL1 {
	if x != nil {
		if x, ok := x.Data.(*MarketData_Tick); ok {
			return x.Tick
		}
	}
	return nil
}

func (x *MarketData) GetFunding() *Funding {
	if x != nil {
		if x, ok := x.Data.(*MarketData_Funding); ok {
			return x.Funding
		}
	}
	return nil
}

func (x *MarketData) GetFee() *Fee {
	if x != nil {
		if x, ok := x.Data.(*MarketData_Fee); ok {
			return x.Fee
		}
	}
	return nil
}

func (x *MarketData) GetTrade() *Trade {
	if x != nil {
		if x, ok := x.Data.(*MarketData_Trade); ok {
			return x.Trade
		}
	}
	return nil
}

type isMarketData_Data interface {
	isMarketData_Data()
}

type MarketData_Tick struct {
	Tick *TickL1 `protobuf:"bytes,10,opt,name=tick,proto3,oneof"`
}

type MarketData_Funding struct {
	Funding *Funding `protobuf:"bytes,11,opt,name=funding,proto3,oneof"`
}

type MarketData_Fee struct {
	Fee *Fee `protobuf:"bytes,12,opt,name=fee,proto3,oneof"`
}

type MarketData_Trade struct {
	Trade *Trade `protobuf:"bytes,13,opt,name=trade,proto3,oneof"`
}

func (*MarketData_Tick) isMarketData_Data() {}

func (*MarketData_Funding) isMarketData_Data() {}

func (*MarketData_Fee) isMarketData_Data() {}

func (*MarketData_Trade) isMarketData_Data() {}

var File_market_proto protoreflect.FileDescriptor

const file_market_proto_rawDesc = "" +
	"\n" +
	"\fmarket.proto\x12\x02md\"\x82\x02\n" +
	"\x06Header\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1f\n" +
	"\x05venue\x18\x03 \x01(\x0e2\t.md.VenueR\x05venue\x12.\n" +
	"\n" +
	"instrument\x18\x04 \x01(\x0e2\x0e.md.InstrumentR\n" +
	"instrument\x12\x13\n" +
	"\x05ts_ns\x18\x05 \x01(\x03R\x04tsNs\x12%\n" +
	"\x0eschema_version\x18\x06 \x01(\rR\rschemaVersion\x12\x14\n" +
	"\x05chain\x18\a \x01(\tR\x05chain\x12!\n" +
	"\fpool_address\x18\b \x01(\tR\vpoolAddress\"\xa6\x01\n" +
	"\x06TickL1\x12\x10\n" +
	"\x03bid\x18\x01 \x01(\x01R\x03bid\x12\x10\n" +
	"\x03ask\x18\x02 \x01(\x01R\x03ask\x12\x10\n" +
	"\x03mid\x18\x03 \x01(\x01R\x03mid\x12\x19\n" +
	"\bbid_size\x18\x04 \x01(\x01R\abidSize\x12\x19\n" +
	"\bask_size\x18\x05 \x01(\x01R\aaskSize\x12\x12\n" +
	"\x04twap\x18\n" +
	" \x01(\x01R\x04twap\x12\x1c\n" +
	"\tliquidity\x18\v \x01(\x01R\tliquidity\"\xce\x01\n" +
	"\aFunding\x12\x1d\n" +
	"\n" +
	"mark_price\x18\x01 \x01(\x01R\tmarkPrice\x12\x1f\n" +
	"\vindex_price\x18\x02 \x01(\x01R\n" +
	"indexPrice\x124\n" +
	"\x16estimated_settle_price\x18\x03 \x01(\x01R\x14estimatedSettlePrice\x12!\n" +
	"\ffunding_rate\x18\x04 \x01(\x01R\vfundingRate\x12*\n" +
	"\x11next_funding_time\x18\x05 \x01(\x03R\x0fnextFundingTime\"C\n" +
	"\x03Fee\x12\x1d\n" +
	"\n" +
	"maker_rate\x18\x01 \x01(\x01R\tmakerRate\x12\x1d\n" +
	"\n" +
	"taker_rate\x18\x02 \x01(\x01R\ttakerRate\"^\n" +
	"\x05Trade\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x01R\x04size\x12+\n" +
	"\taggressor\x18\x03 \x01(\x0e2\r.md.AggressorR\taggressor\"\xc3\x01\n" +
	"\n" +
	"MarketData\x12\"\n" +
	"\x06header\x18\x01 \x01(\v2\n" +
	".md.HeaderR\x06header\x12 \n" +
	"\x04tick\x18\n" +
	" \x01(\v2\n" +
	".md.TickL1H\x00R\x04tick\x12'\n" +
	"\afunding\x18\v \x01(\v2\v.md.FundingH\x00R\afunding\x12\x1b\n" +
	"\x03fee\x18\f \x01(\v2\a.md.FeeH\x00R\x03fee\x12!\n" +
	"\x05trade\x18\r \x01(\v2\t.md.TradeH\x00R\x05tradeB\x06\n" +
	"\x04data*<\n" +
	"\x05Venue\x12\x15\n" +
	"\x11VENUE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tVENUE_CEX\x10\x01\x12\r\n" +
	"\tVENUE_DEX\x10\x02*\x83\x01\n" +
	"\n" +
	"Instrument\x12\x1a\n" +
	"\x16INSTRUMENT_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fINSTRUMENT_SPOT\x10\x01\x12\x18\n" +
	"\x14INSTRUMENT_PERPETUAL\x10\x02\x12\x13\n" +
	"\x0fINSTRUMENT_SWAP\x10\x03\x12\x15\n" +
	"\x11INSTRUMENT_OPTION\x10\x04*:\n" +
	"\tAggressor\x12\x10\n" +
	"\fAGGR_UNKNOWN\x10\x00\x12\f\n" +
	"\bAGGR_BUY\x10\x01\x12\r\n" +
	"\tAGGR_SELL\x10\x02Bl\n" +
	"\x06com.mdB\vMarketProtoP\x01Z-github.com/sujine/market-fetcher/proto;market\xa2\x02\x03MXX\xaa\x02\x02Md\xca\x02\x02Md\xe2\x02\x0eMd\\GPBMetadata\xea\x02\x02Mdb\x06proto3"

var (
	file_market_proto_rawDescOnce sync.Once
	file_market_proto_rawDescData []byte
)

func file_market_proto_rawDescGZIP() []byte {
	file_market_proto_rawDescOnce.Do(func() {
		file_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_proto_rawDesc), len(file_market_proto_rawDesc)))
	})
	return file_market_proto_rawDescData
}

var file_market_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_market_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_market_proto_goTypes = []any{
	(Venue)(0),         // 0: md.Venue
	(Instrument)(0),    // 1: md.Instrument
	(Aggressor)(0),     // 2: md.Aggressor
	(*Header)(nil),     // 3: md.Header
	(*TickL1)(nil),     // 4: md.TickL1
	(*Funding)(nil),    // 5: md.Funding
	(*Fee)(nil),        // 6: md.Fee
	(*Trade)(nil),      // 7: md.Trade
	(*MarketData)(nil), // 8: md.MarketData
}
var file_market_proto_depIdxs = []int32{
	0, // 0: md.Header.venue:type_name -> md.Venue
	1, // 1: md.Header.instrument:type_name -> md.Instrument
	2, // 2: md.Trade.aggressor:type_name -> md.Aggressor
	3, // 3: md.MarketData.header:type_name -> md.Header
	4, // 4: md.MarketData.tick:type_name -> md.TickL1
	5, // 5: md.MarketData.funding:type_name -> md.Funding
	6, // 6: md.MarketData.fee:type_name -> md.Fee
	7, // 7: md.MarketData.trade:type_name -> md.Trade
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_market_proto_init() }
func file_market_proto_init() {
	if File_market_proto != nil {
		return
	}
	file_market_proto_msgTypes[5].OneofWrappers = []any{
		(*MarketData_Tick)(nil),
		(*MarketData_Funding)(nil),
		(*MarketData_Fee)(nil),
		(*MarketData_Trade)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_proto_rawDesc), len(file_market_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_market_proto_goTypes,
		DependencyIndexes: file_market_proto_depIdxs,
		EnumInfos:         file_market_proto_enumTypes,
		MessageInfos:      file_market_proto_msgTypes,
	}.Build()
	File_market_proto = out.File
	file_market_proto_goTypes = nil
	file_market_proto_depIdxs = nil
}
