// marketdata_v2.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: market.proto

package market

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ---- Enums ----
type Venue int32

const (
	Venue_VENUE_UNSPECIFIED Venue = 0
	Venue_VENUE_CEX         Venue = 1
	Venue_VENUE_DEX         Venue = 2
)

// Enum value maps for Venue.
var (
	Venue_name = map[int32]string{
		0: "VENUE_UNSPECIFIED",
		1: "VENUE_CEX",
		2: "VENUE_DEX",
	}
	Venue_value = map[string]int32{
		"VENUE_UNSPECIFIED": 0,
		"VENUE_CEX":         1,
		"VENUE_DEX":         2,
	}
)

func (x Venue) Enum() *Venue {
	p := new(Venue)
	*p = x
	return p
}

func (x Venue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Venue) Descriptor() protoreflect.EnumDescriptor {
	return file_market_proto_enumTypes[0].Descriptor()
}

func (Venue) Type() protoreflect.EnumType {
	return &file_market_proto_enumTypes[0]
}

func (x Venue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Venue.Descriptor instead.
func (Venue) EnumDescriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{0}
}

type Instrument int32

const (
	Instrument_INSTRUMENT_UNSPECIFIED Instrument = 0
	Instrument_INSTRUMENT_SPOT        Instrument = 1
	Instrument_INSTRUMENT_PERPETUAL   Instrument = 2
	Instrument_INSTRUMENT_SWAP        Instrument = 3
	Instrument_INSTRUMENT_OPTION      Instrument = 4 // reserved for future use
)

// Enum value maps for Instrument.
var (
	Instrument_name = map[int32]string{
		0: "INSTRUMENT_UNSPECIFIED",
		1: "INSTRUMENT_SPOT",
		2: "INSTRUMENT_PERPETUAL",
		3: "INSTRUMENT_SWAP",
		4: "INSTRUMENT_OPTION",
	}
	Instrument_value = map[string]int32{
		"INSTRUMENT_UNSPECIFIED": 0,
		"INSTRUMENT_SPOT":        1,
		"INSTRUMENT_PERPETUAL":   2,
		"INSTRUMENT_SWAP":        3,
		"INSTRUMENT_OPTION":      4,
	}
)

func (x Instrument) Enum() *Instrument {
	p := new(Instrument)
	*p = x
	return p
}

func (x Instrument) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Instrument) Descriptor() protoreflect.EnumDescriptor {
	return file_market_proto_enumTypes[1].Descriptor()
}

func (Instrument) Type() protoreflect.EnumType {
	return &file_market_proto_enumTypes[1]
}

func (x Instrument) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Instrument.Descriptor instead.
func (Instrument) EnumDescriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{1}
}

type Aggressor int32

const (
	Aggressor_AGGR_UNKNOWN Aggressor = 0
	Aggressor_AGGR_BUY     Aggressor = 1
	Aggressor_AGGR_SELL    Aggressor = 2
)

// Enum value maps for Aggressor.
var (
	Aggressor_name = map[int32]string{
		0: "AGGR_UNKNOWN",
		1: "AGGR_BUY",
		2: "AGGR_SELL",
	}
	Aggressor_value = map[string]int32{
		"AGGR_UNKNOWN": 0,
		"AGGR_BUY":     1,
		"AGGR_SELL":    2,
	}
)

func (x Aggressor) Enum() *Aggressor {
	p := new(Aggressor)
	*p = x
	return p
}

func (x Aggressor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Aggressor) Descriptor() protoreflect.EnumDescriptor {
	return file_market_proto_enumTypes[2].Descriptor()
}

func (Aggressor) Type() protoreflect.EnumType {
	return &file_market_proto_enumTypes[2]
}

func (x Aggressor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Aggressor.Descriptor instead.
func (Aggressor) EnumDescriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{2}
}

// ---- Common header ----
type Header struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exchange identifier: e.g. "Binance", "PancakeSwapV3"
	Exchange string `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	// Unified symbol: e.g. "ETHUSDT", "BNB-USDT" (keep your house-style)
	Symbol     string     `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Venue      Venue      `protobuf:"varint,3,opt,name=venue,proto3,enum=md.Venue" json:"venue,omitempty"`
	Instrument Instrument `protobuf:"varint,4,opt,name=instrument,proto3,enum=md.Instrument" json:"instrument,omitempty"`
	// Monotonic-ish, event emission time in ns (UTC).
	TsNs int64 `protobuf:"varint,5,opt,name=ts_ns,json=tsNs,proto3" json:"ts_ns,omitempty"`
	// Schema version for the event family (bump when breaking).
	SchemaVersion uint32 `protobuf:"varint,6,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// Optional chain context for DEX (e.g., "BSC"), else empty.
	Chain string `protobuf:"bytes,7,opt,name=chain,proto3" json:"chain,omitempty"`
	// Optional: raw pool address for DEX tick source.
	PoolAddress   string `protobuf:"bytes,8,opt,name=pool_address,json=poolAddress,proto3" json:"pool_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *Header) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Header) GetVenue() Venue {
	if x != nil {
		return x.Venue
	}
	return Venue_VENUE_UNSPECIFIED
}

func (x *Header) GetInstrument() Instrument {
	if x != nil {
		return x.Instrument
	}
	return Instrument_INSTRUMENT_UNSPECIFIED
}

func (x *Header) GetTsNs() int64 {
	if x != nil {
		return x.TsNs
	}
	return 0
}

func (x *Header) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Header) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *Header) GetPoolAddress() string {
	if x != nil {
		return x.PoolAddress
	}
	return ""
}

// ---- Normalized events ----
type TickL1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Best bid/ask. If not available (DEX mark-only), set bid/ask = 0 and use mid.
	Bid           float64 `protobuf:"fixed64,1,opt,name=bid,proto3" json:"bid,omitempty"`
	Ask           float64 `protobuf:"fixed64,2,opt,name=ask,proto3" json:"ask,omitempty"`
	Mid           float64 `protobuf:"fixed64,3,opt,name=mid,proto3" json:"mid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickL1) Reset() {
	*x = TickL1{}
	mi := &file_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickL1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickL1) ProtoMessage() {}

func (x *TickL1) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickL1.ProtoReflect.Descriptor instead.
func (*TickL1) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{1}
}

func (x *TickL1) GetBid() float64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *TickL1) GetAsk() float64 {
	if x != nil {
		return x.Ask
	}
	return 0
}

func (x *TickL1) GetMid() float64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

type DexSwapL1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// --- Raw swap event fields (as emitted by the pool) ---
	// Signed amounts (string to keep precision): amount0<0 means token0 leaves pool (user pays token0)
	Amount0 string `protobuf:"bytes,1,opt,name=amount0,proto3" json:"amount0,omitempty"` // int256 string
	Amount1 string `protobuf:"bytes,2,opt,name=amount1,proto3" json:"amount1,omitempty"` // int256 string
	// Pool state after the swap
	SqrtPriceX96  string `protobuf:"bytes,10,opt,name=sqrt_price_x96,json=sqrtPriceX96,proto3" json:"sqrt_price_x96,omitempty"`  // uint160 as string
	Tick          int32  `protobuf:"zigzag32,11,opt,name=tick,proto3" json:"tick,omitempty"`                                     // int24 fits in sint32
	LiquidityU128 string `protobuf:"bytes,12,opt,name=liquidity_u128,json=liquidityU128,proto3" json:"liquidity_u128,omitempty"` // uint128 as string
	// Fees accrued to protocol (if present in event/log)
	ProtocolFeesToken0 string `protobuf:"bytes,13,opt,name=protocol_fees_token0,json=protocolFeesToken0,proto3" json:"protocol_fees_token0,omitempty"` // uint128 as string
	ProtocolFeesToken1 string `protobuf:"bytes,14,opt,name=protocol_fees_token1,json=protocolFeesToken1,proto3" json:"protocol_fees_token1,omitempty"` // uint128 as string
	// --- Context / identity ---
	TxHash      string `protobuf:"bytes,21,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`                 // transaction hash (0x…)
	LogIndex    uint64 `protobuf:"varint,22,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`          // log index within the tx
	BlockNumber uint64 `protobuf:"varint,23,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"` // block number
	Timestamp   uint64 `protobuf:"varint,24,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                        // unix seconds
	// --- Token metadata (to compute human price) ---
	Token0         string `protobuf:"bytes,30,opt,name=token0,proto3" json:"token0,omitempty"`                                        // symbol
	Token1         string `protobuf:"bytes,31,opt,name=token1,proto3" json:"token1,omitempty"`                                        // symbol
	Token0Decimals uint32 `protobuf:"varint,32,opt,name=token0_decimals,json=token0Decimals,proto3" json:"token0_decimals,omitempty"` // e.g., 18
	Token1Decimals uint32 `protobuf:"varint,33,opt,name=token1_decimals,json=token1Decimals,proto3" json:"token1_decimals,omitempty"` // e.g., 18
	// --- Orientation & computed prices ---
	// price01 = token1/token0 (pool-native). price_qb = quote/base as requested by the symbol.
	InvertForQuote bool    `protobuf:"varint,40,opt,name=invert_for_quote,json=invertForQuote,proto3" json:"invert_for_quote,omitempty"` // true if we inverted price01 to form quote/base
	Price01        float64 `protobuf:"fixed64,41,opt,name=price01,proto3" json:"price01,omitempty"`                                      // price = (sqrtP/2^96)^2 * 10^(dec0-dec1)
	Price10        float64 `protobuf:"fixed64,42,opt,name=price10,proto3" json:"price10,omitempty"`                                      // price after invert if needed (what you publish as “mid”)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DexSwapL1) Reset() {
	*x = DexSwapL1{}
	mi := &file_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DexSwapL1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DexSwapL1) ProtoMessage() {}

func (x *DexSwapL1) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DexSwapL1.ProtoReflect.Descriptor instead.
func (*DexSwapL1) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{2}
}

func (x *DexSwapL1) GetAmount0() string {
	if x != nil {
		return x.Amount0
	}
	return ""
}

func (x *DexSwapL1) GetAmount1() string {
	if x != nil {
		return x.Amount1
	}
	return ""
}

func (x *DexSwapL1) GetSqrtPriceX96() string {
	if x != nil {
		return x.SqrtPriceX96
	}
	return ""
}

func (x *DexSwapL1) GetTick() int32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *DexSwapL1) GetLiquidityU128() string {
	if x != nil {
		return x.LiquidityU128
	}
	return ""
}

func (x *DexSwapL1) GetProtocolFeesToken0() string {
	if x != nil {
		return x.ProtocolFeesToken0
	}
	return ""
}

func (x *DexSwapL1) GetProtocolFeesToken1() string {
	if x != nil {
		return x.ProtocolFeesToken1
	}
	return ""
}

func (x *DexSwapL1) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *DexSwapL1) GetLogIndex() uint64 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

func (x *DexSwapL1) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *DexSwapL1) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DexSwapL1) GetToken0() string {
	if x != nil {
		return x.Token0
	}
	return ""
}

func (x *DexSwapL1) GetToken1() string {
	if x != nil {
		return x.Token1
	}
	return ""
}

func (x *DexSwapL1) GetToken0Decimals() uint32 {
	if x != nil {
		return x.Token0Decimals
	}
	return 0
}

func (x *DexSwapL1) GetToken1Decimals() uint32 {
	if x != nil {
		return x.Token1Decimals
	}
	return 0
}

func (x *DexSwapL1) GetInvertForQuote() bool {
	if x != nil {
		return x.InvertForQuote
	}
	return false
}

func (x *DexSwapL1) GetPrice01() float64 {
	if x != nil {
		return x.Price01
	}
	return 0
}

func (x *DexSwapL1) GetPrice10() float64 {
	if x != nil {
		return x.Price10
	}
	return 0
}

type Slippage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImpactBps01   float64                `protobuf:"fixed64,1,opt,name=impact_bps01,json=impactBps01,proto3" json:"impact_bps01,omitempty"`
	ImpactBps10   float64                `protobuf:"fixed64,2,opt,name=impact_bps10,json=impactBps10,proto3" json:"impact_bps10,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,3,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	TxHash        string                 `protobuf:"bytes,4,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Slippage) Reset() {
	*x = Slippage{}
	mi := &file_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slippage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slippage) ProtoMessage() {}

func (x *Slippage) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slippage.ProtoReflect.Descriptor instead.
func (*Slippage) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{3}
}

func (x *Slippage) GetImpactBps01() float64 {
	if x != nil {
		return x.ImpactBps01
	}
	return 0
}

func (x *Slippage) GetImpactBps10() float64 {
	if x != nil {
		return x.ImpactBps10
	}
	return 0
}

func (x *Slippage) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *Slippage) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *Slippage) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Volume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume0       float64                `protobuf:"fixed64,1,opt,name=volume0,proto3" json:"volume0,omitempty"`
	Volume1       float64                `protobuf:"fixed64,2,opt,name=volume1,proto3" json:"volume1,omitempty"`
	High          float64                `protobuf:"fixed64,3,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,4,opt,name=low,proto3" json:"low,omitempty"`
	Trades        uint64                 `protobuf:"varint,5,opt,name=trades,proto3" json:"trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Volume) Reset() {
	*x = Volume{}
	mi := &file_market_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Volume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volume) ProtoMessage() {}

func (x *Volume) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volume.ProtoReflect.Descriptor instead.
func (*Volume) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{4}
}

func (x *Volume) GetVolume0() float64 {
	if x != nil {
		return x.Volume0
	}
	return 0
}

func (x *Volume) GetVolume1() float64 {
	if x != nil {
		return x.Volume1
	}
	return 0
}

func (x *Volume) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Volume) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Volume) GetTrades() uint64 {
	if x != nil {
		return x.Trades
	}
	return 0
}

type Funding struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MarkPrice            float64                `protobuf:"fixed64,1,opt,name=mark_price,json=markPrice,proto3" json:"mark_price,omitempty"`
	IndexPrice           float64                `protobuf:"fixed64,2,opt,name=index_price,json=indexPrice,proto3" json:"index_price,omitempty"`
	EstimatedSettlePrice float64                `protobuf:"fixed64,3,opt,name=estimated_settle_price,json=estimatedSettlePrice,proto3" json:"estimated_settle_price,omitempty"`
	FundingRate          float64                `protobuf:"fixed64,4,opt,name=funding_rate,json=fundingRate,proto3" json:"funding_rate,omitempty"`              // per-period rate (e.g., 8h)
	NextFundingTime      int64                  `protobuf:"varint,5,opt,name=next_funding_time,json=nextFundingTime,proto3" json:"next_funding_time,omitempty"` // ms since epoch (exchange native)
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Funding) Reset() {
	*x = Funding{}
	mi := &file_market_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Funding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Funding) ProtoMessage() {}

func (x *Funding) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Funding.ProtoReflect.Descriptor instead.
func (*Funding) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{5}
}

func (x *Funding) GetMarkPrice() float64 {
	if x != nil {
		return x.MarkPrice
	}
	return 0
}

func (x *Funding) GetIndexPrice() float64 {
	if x != nil {
		return x.IndexPrice
	}
	return 0
}

func (x *Funding) GetEstimatedSettlePrice() float64 {
	if x != nil {
		return x.EstimatedSettlePrice
	}
	return 0
}

func (x *Funding) GetFundingRate() float64 {
	if x != nil {
		return x.FundingRate
	}
	return 0
}

func (x *Funding) GetNextFundingTime() int64 {
	if x != nil {
		return x.NextFundingTime
	}
	return 0
}

type Fee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MakerRate     float64                `protobuf:"fixed64,1,opt,name=maker_rate,json=makerRate,proto3" json:"maker_rate,omitempty"` // ratio (e.g., 0.001)
	TakerRate     float64                `protobuf:"fixed64,2,opt,name=taker_rate,json=takerRate,proto3" json:"taker_rate,omitempty"` // ratio
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fee) Reset() {
	*x = Fee{}
	mi := &file_market_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fee) ProtoMessage() {}

func (x *Fee) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fee.ProtoReflect.Descriptor instead.
func (*Fee) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{6}
}

func (x *Fee) GetMakerRate() float64 {
	if x != nil {
		return x.MakerRate
	}
	return 0
}

func (x *Fee) GetTakerRate() float64 {
	if x != nil {
		return x.TakerRate
	}
	return 0
}

type Trade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Size          float64                `protobuf:"fixed64,2,opt,name=size,proto3" json:"size,omitempty"`
	Aggressor     Aggressor              `protobuf:"varint,3,opt,name=aggressor,proto3,enum=md.Aggressor" json:"aggressor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_market_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{7}
}

func (x *Trade) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Trade) GetSize() float64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Trade) GetAggressor() Aggressor {
	if x != nil {
		return x.Aggressor
	}
	return Aggressor_AGGR_UNKNOWN
}

// ---- Envelope ----
type MarketData struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*MarketData_Tick
	//	*MarketData_DexSwapL1
	//	*MarketData_Funding
	//	*MarketData_Fee
	//	*MarketData_Trade
	//	*MarketData_Volume
	//	*MarketData_Slippage
	Data          isMarketData_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketData) Reset() {
	*x = MarketData{}
	mi := &file_market_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketData) ProtoMessage() {}

func (x *MarketData) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketData.ProtoReflect.Descriptor instead.
func (*MarketData) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{8}
}

func (x *MarketData) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *MarketData) GetData() isMarketData_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MarketData) GetTick() *TickL1 {
	if x != nil {
		if x, ok := x.Data.(*MarketData_Tick); ok {
			return x.Tick
		}
	}
	return nil
}

func (x *MarketData) GetDexSwapL1() *DexSwapL1 {
	if x != nil {
		if x, ok := x.Data.(*MarketData_DexSwapL1); ok {
			return x.DexSwapL1
		}
	}
	return nil
}

func (x *MarketData) GetFunding() *Funding {
	if x != nil {
		if x, ok := x.Data.(*MarketData_Funding); ok {
			return x.Funding
		}
	}
	return nil
}

func (x *MarketData) GetFee() *Fee {
	if x != nil {
		if x, ok := x.Data.(*MarketData_Fee); ok {
			return x.Fee
		}
	}
	return nil
}

func (x *MarketData) GetTrade() *Trade {
	if x != nil {
		if x, ok := x.Data.(*MarketData_Trade); ok {
			return x.Trade
		}
	}
	return nil
}

func (x *MarketData) GetVolume() *Volume {
	if x != nil {
		if x, ok := x.Data.(*MarketData_Volume); ok {
			return x.Volume
		}
	}
	return nil
}

func (x *MarketData) GetSlippage() *Slippage {
	if x != nil {
		if x, ok := x.Data.(*MarketData_Slippage); ok {
			return x.Slippage
		}
	}
	return nil
}

type isMarketData_Data interface {
	isMarketData_Data()
}

type MarketData_Tick struct {
	Tick *TickL1 `protobuf:"bytes,10,opt,name=tick,proto3,oneof"`
}

type MarketData_DexSwapL1 struct {
	DexSwapL1 *DexSwapL1 `protobuf:"bytes,11,opt,name=dexSwapL1,proto3,oneof"`
}

type MarketData_Funding struct {
	Funding *Funding `protobuf:"bytes,12,opt,name=funding,proto3,oneof"`
}

type MarketData_Fee struct {
	Fee *Fee `protobuf:"bytes,13,opt,name=fee,proto3,oneof"`
}

type MarketData_Trade struct {
	Trade *Trade `protobuf:"bytes,14,opt,name=trade,proto3,oneof"`
}

type MarketData_Volume struct {
	Volume *Volume `protobuf:"bytes,15,opt,name=volume,proto3,oneof"`
}

type MarketData_Slippage struct {
	Slippage *Slippage `protobuf:"bytes,16,opt,name=slippage,proto3,oneof"`
}

func (*MarketData_Tick) isMarketData_Data() {}

func (*MarketData_DexSwapL1) isMarketData_Data() {}

func (*MarketData_Funding) isMarketData_Data() {}

func (*MarketData_Fee) isMarketData_Data() {}

func (*MarketData_Trade) isMarketData_Data() {}

func (*MarketData_Volume) isMarketData_Data() {}

func (*MarketData_Slippage) isMarketData_Data() {}

var File_market_proto protoreflect.FileDescriptor

const file_market_proto_rawDesc = "" +
	"\n" +
	"\fmarket.proto\x12\x02md\"\x82\x02\n" +
	"\x06Header\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1f\n" +
	"\x05venue\x18\x03 \x01(\x0e2\t.md.VenueR\x05venue\x12.\n" +
	"\n" +
	"instrument\x18\x04 \x01(\x0e2\x0e.md.InstrumentR\n" +
	"instrument\x12\x13\n" +
	"\x05ts_ns\x18\x05 \x01(\x03R\x04tsNs\x12%\n" +
	"\x0eschema_version\x18\x06 \x01(\rR\rschemaVersion\x12\x14\n" +
	"\x05chain\x18\a \x01(\tR\x05chain\x12!\n" +
	"\fpool_address\x18\b \x01(\tR\vpoolAddress\">\n" +
	"\x06TickL1\x12\x10\n" +
	"\x03bid\x18\x01 \x01(\x01R\x03bid\x12\x10\n" +
	"\x03ask\x18\x02 \x01(\x01R\x03ask\x12\x10\n" +
	"\x03mid\x18\x03 \x01(\x01R\x03mid\"\xdb\x04\n" +
	"\tDexSwapL1\x12\x18\n" +
	"\aamount0\x18\x01 \x01(\tR\aamount0\x12\x18\n" +
	"\aamount1\x18\x02 \x01(\tR\aamount1\x12$\n" +
	"\x0esqrt_price_x96\x18\n" +
	" \x01(\tR\fsqrtPriceX96\x12\x12\n" +
	"\x04tick\x18\v \x01(\x11R\x04tick\x12%\n" +
	"\x0eliquidity_u128\x18\f \x01(\tR\rliquidityU128\x120\n" +
	"\x14protocol_fees_token0\x18\r \x01(\tR\x12protocolFeesToken0\x120\n" +
	"\x14protocol_fees_token1\x18\x0e \x01(\tR\x12protocolFeesToken1\x12\x17\n" +
	"\atx_hash\x18\x15 \x01(\tR\x06txHash\x12\x1b\n" +
	"\tlog_index\x18\x16 \x01(\x04R\blogIndex\x12!\n" +
	"\fblock_number\x18\x17 \x01(\x04R\vblockNumber\x12\x1c\n" +
	"\ttimestamp\x18\x18 \x01(\x04R\ttimestamp\x12\x16\n" +
	"\x06token0\x18\x1e \x01(\tR\x06token0\x12\x16\n" +
	"\x06token1\x18\x1f \x01(\tR\x06token1\x12'\n" +
	"\x0ftoken0_decimals\x18  \x01(\rR\x0etoken0Decimals\x12'\n" +
	"\x0ftoken1_decimals\x18! \x01(\rR\x0etoken1Decimals\x12(\n" +
	"\x10invert_for_quote\x18( \x01(\bR\x0einvertForQuote\x12\x18\n" +
	"\aprice01\x18) \x01(\x01R\aprice01\x12\x18\n" +
	"\aprice10\x18* \x01(\x01R\aprice10\"\xaa\x01\n" +
	"\bSlippage\x12!\n" +
	"\fimpact_bps01\x18\x01 \x01(\x01R\vimpactBps01\x12!\n" +
	"\fimpact_bps10\x18\x02 \x01(\x01R\vimpactBps10\x12!\n" +
	"\fblock_number\x18\x03 \x01(\x04R\vblockNumber\x12\x17\n" +
	"\atx_hash\x18\x04 \x01(\tR\x06txHash\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x04R\ttimestamp\"z\n" +
	"\x06Volume\x12\x18\n" +
	"\avolume0\x18\x01 \x01(\x01R\avolume0\x12\x18\n" +
	"\avolume1\x18\x02 \x01(\x01R\avolume1\x12\x12\n" +
	"\x04high\x18\x03 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x04 \x01(\x01R\x03low\x12\x16\n" +
	"\x06trades\x18\x05 \x01(\x04R\x06trades\"\xce\x01\n" +
	"\aFunding\x12\x1d\n" +
	"\n" +
	"mark_price\x18\x01 \x01(\x01R\tmarkPrice\x12\x1f\n" +
	"\vindex_price\x18\x02 \x01(\x01R\n" +
	"indexPrice\x124\n" +
	"\x16estimated_settle_price\x18\x03 \x01(\x01R\x14estimatedSettlePrice\x12!\n" +
	"\ffunding_rate\x18\x04 \x01(\x01R\vfundingRate\x12*\n" +
	"\x11next_funding_time\x18\x05 \x01(\x03R\x0fnextFundingTime\"C\n" +
	"\x03Fee\x12\x1d\n" +
	"\n" +
	"maker_rate\x18\x01 \x01(\x01R\tmakerRate\x12\x1d\n" +
	"\n" +
	"taker_rate\x18\x02 \x01(\x01R\ttakerRate\"^\n" +
	"\x05Trade\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x01R\x04size\x12+\n" +
	"\taggressor\x18\x03 \x01(\x0e2\r.md.AggressorR\taggressor\"\xc4\x02\n" +
	"\n" +
	"MarketData\x12\"\n" +
	"\x06header\x18\x01 \x01(\v2\n" +
	".md.HeaderR\x06header\x12 \n" +
	"\x04tick\x18\n" +
	" \x01(\v2\n" +
	".md.TickL1H\x00R\x04tick\x12-\n" +
	"\tdexSwapL1\x18\v \x01(\v2\r.md.DexSwapL1H\x00R\tdexSwapL1\x12'\n" +
	"\afunding\x18\f \x01(\v2\v.md.FundingH\x00R\afunding\x12\x1b\n" +
	"\x03fee\x18\r \x01(\v2\a.md.FeeH\x00R\x03fee\x12!\n" +
	"\x05trade\x18\x0e \x01(\v2\t.md.TradeH\x00R\x05trade\x12$\n" +
	"\x06volume\x18\x0f \x01(\v2\n" +
	".md.VolumeH\x00R\x06volume\x12*\n" +
	"\bslippage\x18\x10 \x01(\v2\f.md.SlippageH\x00R\bslippageB\x06\n" +
	"\x04data*<\n" +
	"\x05Venue\x12\x15\n" +
	"\x11VENUE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tVENUE_CEX\x10\x01\x12\r\n" +
	"\tVENUE_DEX\x10\x02*\x83\x01\n" +
	"\n" +
	"Instrument\x12\x1a\n" +
	"\x16INSTRUMENT_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fINSTRUMENT_SPOT\x10\x01\x12\x18\n" +
	"\x14INSTRUMENT_PERPETUAL\x10\x02\x12\x13\n" +
	"\x0fINSTRUMENT_SWAP\x10\x03\x12\x15\n" +
	"\x11INSTRUMENT_OPTION\x10\x04*:\n" +
	"\tAggressor\x12\x10\n" +
	"\fAGGR_UNKNOWN\x10\x00\x12\f\n" +
	"\bAGGR_BUY\x10\x01\x12\r\n" +
	"\tAGGR_SELL\x10\x02Bl\n" +
	"\x06com.mdB\vMarketProtoP\x01Z-github.com/sujine/market-fetcher/proto;market\xa2\x02\x03MXX\xaa\x02\x02Md\xca\x02\x02Md\xe2\x02\x0eMd\\GPBMetadata\xea\x02\x02Mdb\x06proto3"

var (
	file_market_proto_rawDescOnce sync.Once
	file_market_proto_rawDescData []byte
)

func file_market_proto_rawDescGZIP() []byte {
	file_market_proto_rawDescOnce.Do(func() {
		file_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_proto_rawDesc), len(file_market_proto_rawDesc)))
	})
	return file_market_proto_rawDescData
}

var file_market_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_market_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_market_proto_goTypes = []any{
	(Venue)(0),         // 0: md.Venue
	(Instrument)(0),    // 1: md.Instrument
	(Aggressor)(0),     // 2: md.Aggressor
	(*Header)(nil),     // 3: md.Header
	(*TickL1)(nil),     // 4: md.TickL1
	(*DexSwapL1)(nil),  // 5: md.DexSwapL1
	(*Slippage)(nil),   // 6: md.Slippage
	(*Volume)(nil),     // 7: md.Volume
	(*Funding)(nil),    // 8: md.Funding
	(*Fee)(nil),        // 9: md.Fee
	(*Trade)(nil),      // 10: md.Trade
	(*MarketData)(nil), // 11: md.MarketData
}
var file_market_proto_depIdxs = []int32{
	0,  // 0: md.Header.venue:type_name -> md.Venue
	1,  // 1: md.Header.instrument:type_name -> md.Instrument
	2,  // 2: md.Trade.aggressor:type_name -> md.Aggressor
	3,  // 3: md.MarketData.header:type_name -> md.Header
	4,  // 4: md.MarketData.tick:type_name -> md.TickL1
	5,  // 5: md.MarketData.dexSwapL1:type_name -> md.DexSwapL1
	8,  // 6: md.MarketData.funding:type_name -> md.Funding
	9,  // 7: md.MarketData.fee:type_name -> md.Fee
	10, // 8: md.MarketData.trade:type_name -> md.Trade
	7,  // 9: md.MarketData.volume:type_name -> md.Volume
	6,  // 10: md.MarketData.slippage:type_name -> md.Slippage
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_market_proto_init() }
func file_market_proto_init() {
	if File_market_proto != nil {
		return
	}
	file_market_proto_msgTypes[8].OneofWrappers = []any{
		(*MarketData_Tick)(nil),
		(*MarketData_DexSwapL1)(nil),
		(*MarketData_Funding)(nil),
		(*MarketData_Fee)(nil),
		(*MarketData_Trade)(nil),
		(*MarketData_Volume)(nil),
		(*MarketData_Slippage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_proto_rawDesc), len(file_market_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_market_proto_goTypes,
		DependencyIndexes: file_market_proto_depIdxs,
		EnumInfos:         file_market_proto_enumTypes,
		MessageInfos:      file_market_proto_msgTypes,
	}.Build()
	File_market_proto = out.File
	file_market_proto_goTypes = nil
	file_market_proto_depIdxs = nil
}
